login:
    path: /login
    controller: App\Controller\SecurityController::login

registration:
    path: /registration
    controller: App\Controller\UserController::showRegistrationForm

add_user:
    path: /register_user
    controller: App\Controller\UserController::registerUser

# login_user:
#     path: /login_user
#     methods: POST
#     controller: App\Controller\UserController::loginUser

show_home:
    path: /home
    methods: GET
    controller: App\Controller\StorefrontController::showHome

show_home_index: 
    path: /index
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: show_home

show_home_empty: 
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: show_home

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout